# Generated by Django 4.1.4 on 2024-04-07 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='D_Customers',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('home_address', models.CharField(max_length=500)),
                ('zip_code', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='D_Orders',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='D_Products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='D_Sales',
            fields=[
                ('sales_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('price_per_unit', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.d_orders')),
            ],
        ),
        migrations.CreateModel(
            name='H_Shopping_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('home_address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=200)),
                ('order_date', models.DateField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.d_customers')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.d_orders')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.d_products')),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.d_sales')),
            ],
        ),
    ]
