# Generated by Django 4.1.4 on 2024-04-07 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_d_sales_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='h_shopping_cart',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='h_shopping_cart',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='h_shopping_cart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='h_shopping_cart',
            old_name='sales_id',
            new_name='sales',
        ),
    ]
